version: '3.9'
services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3500:3500
      - 3001:9229
    networks:
      - booked-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:5
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      - booked-network
    restart: always
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3500:3500
      - 9229:9229
    networks:
      - booked-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
volumes:
  mongo-data: {}

networks:
  booked-network:
    name: booked-network
